// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package models

// ShortenCode defines model for ShortenCode.
type ShortenCode struct {
	// Code The code that can be used to get a redirect to the original page
	Code string `json:"code"`
}

// URL defines model for URL.
type URL struct {
	// Url The url you wish to be shortened
	Url string `json:"url"`
}

// ShortenUrlJSONRequestBody defines body for ShortenUrl for application/json ContentType.
type ShortenUrlJSONRequestBody = URL

// ShortenUrlFormdataRequestBody defines body for ShortenUrl for application/x-www-form-urlencoded ContentType.
type ShortenUrlFormdataRequestBody = URL
